config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      patch :toggle_status
    end
  end

  resources :portfolios, except: [:show] do
    member do
      patch :move
    end
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  DRAFT = 'draft'
  PUBLISHED = 'published'

  enum status: {
    DRAFT => 0,
    PUBLISHED => 1
  }

  belongs_to :topic

  validates_presence_of :title, :body
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy toggle_status]
  access all: %i[show index],
         user: { except: %i[new edit create update destroy toggle_status] },
         site_admin: :all
  layout "blog"

  def index
    @blogs = Blog.page(params[:page]).per(5)
  end

  def show
    @page_title = @blog.title
    @seo_description = @blog.body
  end

  def new
    @blog = Blog.new
  end

  def edit; end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Post was successfully removed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    @blog.draft? ? @blog.published! : @blog.draft!
    redirect_to blogs_url, notice: "Post status has been updated."
  end

  private

    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<article class="blog-post">
  <h2 class="display-5">
    <%= link_to blog.title, blog %>
  </h2>
  <p class="blog-post-meta">
    Published <%= distance_of_time_in_words_to_now(blog.created_at) %> ago
  </p>
  
  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog), data: { "turbo-method" => :patch } %> /
      <%= link_to "Edit", edit_blog_path(blog) %> /
      <%= link_to "Delete Post", blog, data: { "turbo-method": :delete } %>
    </p>
  <% end %>

  <p>
    <%= blog.body %>
  </p>
</article>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.each do |error| %>
      <%= turbo_stream.append "toast" do %>
        <% generate_alert(error.full_message) %>
      <% end %>
    <% end %>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="mb-3">
    <%= form.text_area :body, rows: 12, class: "form-control", placeholder: "Content" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8">
  <h1>Editing blog</h1>

  <%= render "form", blog: @blog %>

  <br>

  <div>
    <%= link_to "Show this blog", @blog %> |
    <%= link_to "Back to blogs", blogs_path %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="col-md-8">
  
  <%= render @blogs %>

  <%= paginate @blogs %>
  
</div>

app/views/blogs/new.html.erb
<div class="col-md-8">
  <h1>New blog</h1>

  <%= render "form", blog: @blog %>

  <br>

  <div>
    <%= link_to "Back to blogs", blogs_path %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8">
  <article class="blog-post">
    <h2 class="display-5 link-body-emphasis mb-1"><%= @blog.title %></h2>
    <p class="blog-post-meta">
      <%= link_to "Edit", edit_blog_path(@blog) if logged_in?(:site_admin) %>
    </p>

    <p>
      <%= @blog.body %>
    </p>
  </article>
</div>