config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      patch :toggle_status
    end
  end

  resources :portfolios, except: [:show] do
    member do
      patch :move
    end
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy

  acts_as_list

  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: proc { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  scope :by_position, -> { order("position ASC") }

  mount_uploader :main_image, PortfolioUploader
  mount_uploader :thumb_image, PortfolioUploader
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[show edit update destroy move]
  access all: %i[show index],
         user: { except: %i[new edit create update destroy move] },
         site_admin: :all
  layout "portfolio"

  def index
    @portfolio_items = Portfolio.by_position
  end

  def show; end

  def new
    @portfolio_item = Portfolio.new
  end

  def edit; end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolio_show_url(@portfolio_item), notice: "Portfolio was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolio_show_url(@portfolio_item), notice: "Portfolio was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Portfolio was successfully removed." }
    end
  end

  def move
    @portfolio_item.insert_at(params[:position].to_i)
    head :no_content
  end

  private

    def set_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(
        :title,
        :subtitle,
        :body,
        :main_image,
        :thumb_image,
        technologies_attributes: %i[id name _destroy]
      )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def portfolio_img(img, type)
    if img.url.present?
      img.url
    elsif type == "main"
      generate_image(width: 600, height: 400)
    elsif type == "thumb"
      generate_image(width: 350, height: 200)
    end
  end

  private

    def generate_image(width:, height:)
      "http://placehold.it/#{width}x#{height}"
    end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item) do |form| %>
  <% if portfolio_item.errors.any? %>
    <% portfolio_item.errors.each do |error| %>
      <%= turbo_stream.append "toast" do %>
        <% generate_alert(error.full_message) %>
      <% end %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :subtitle, class: "form-label" %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>
      <div class="input-group mb-3">
        <%= form.file_field :main_image, class: "form-control" %>
        <%= form.label :main_image, class: "input-group-text" %>
      </div>

      <div class="input-group mb-3">
        <%= form.file_field :thumb_image, class: "form-control" %>
        <%= form.label :thumb_image, class: "input-group-text" %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :body, class: "form-label" %>
        <%= form.text_area :body, class: "form-control", rows: 12 %>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <h3>Technologies used:</h3>

    <div class="technologies-container">
      <div id="technologies">
        <%= form.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', form: technology_form %>
        <% end %>
      </div>

      <div>
        <%= link_to_add_nested(form, :technologies, "#technologies") %>
      </div>
    </div>

    <div class="d-grid mb-3">
      <%= form.submit "Save Portfolio", class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col" data-sortable-update-url="<%= move_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>">
  <div class="card shadow-sm">
    <%= image_tag portfolio_img(portfolio_item.thumb_image, "thumb") %>
    <div class="card-body">
      <p class="card-text">
      	<span><%= portfolio_item.title %></span> <%= portfolio_item.subtitle %>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "View", portfolio_show_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" %>
          <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
        </div>
        <small class="text-body-secondary"><%= distance_of_time_in_words_to_now(portfolio_item.created_at) %></small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="row g-3 technology-container">
  <div class="col-auto">
    <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>
  <div class="col-auto">
    <%= link_to_remove_nested(form, link_classes: "btn btn-danger mb-3", fields_wrapper_selector: ".technology-container") %>
  </div>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" data-controller=<%= "sortable" if logged_in?(:site_admin) %>>
      <%= render partial: "portfolio_item", collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, "main"), width: "100%" %>
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |technology| %>
        <p><%= technology.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>