config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      patch :toggle_status
    end
  end

  resources :portfolios, except: [:show] do
    member do
      patch :move
    end
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
end

app/views/shared/_application_footer.html.erb
<footer class="mt-auto text-white-50">
  <p class="app-footer"><%= copyright %></p>
</footer>

app/views/shared/_application_nav.html.erb
<header class="mb-auto">
  <div>
    <h3 class="float-md-start mb-0">TZ</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
      <%= nav_generator("span", "nav-link fw-bold py-1 px-0") %>
      <%= auth_links("nav-link fw-bold py-1 px-0") %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="py-5 text-center text-body-secondary bg-body-tertiary">
  <p>
    <%= copyright %>
  </p>
  <p class="mb-0">
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
  <div class="col-lg-6 px-0">
    <h1 class="display-4 fst-italic">My Blog</h1>
    <p class="lead my-3">Multiple lines of text informing new readers about what’s most interesting in this blog.</p>
    <p class="lead mb-0">
      <%= link_to "Write a New Blog", new_blog_path, class: "text-body-emphasis fw-bold" if logged_in?(:site_admin) %>    
    </p>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="container">
  <div class="nav-scroller py-1 mb-3 border-bottom">
    <nav class="nav nav-underline justify-content-between">
      <%= nav_generator("span", "nav-item nav-link link-body-emphasis") %>
      <%= auth_links("nav-item nav-link link-body-emphasis") %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-md-4">
  <div class="position-sticky" style="top: 2rem;">
    <div class="p-4 mb-3 bg-body-tertiary rounded">
      <h4 class="fst-italic">About</h4>
      <p class="mb-0">Passionate about software development and interested in learning new domains. Love to write beautiful code, well tested and easy to maintain.</p>
      <p class="mb-0">
        I am a marathoner and long distance triathlete :)
        <%= icon "fa-solid", "person-swimming" %>
        <%= icon "fa-solid", "bicycle" %>
        <%= icon "fa-solid", "person-running" %>
      </p>
    </div>

    <div class="p-4">
      <h4 class="fst-italic">Elsewhere</h4>
      <ol class="list-unstyled social-links">
        <li><a href="https://www.linkedin.com/in/tetiana-zavediuk"><%= icon "fa-brands", "linkedin" %></a></li>
        <li><a href="https://github.com/cervols"><%= icon "fa-brands", "github" %></a></li>
        <li><a href="https://www.facebook.com/tania.zavediuk"><%= icon "fa-brands", "facebook" %></a></li>
        <li><a href="https://www.instagram.com/cervols"><%= icon "fa-brands", "instagram" %></a></li>
      </ol>
    </div>
  </div>
</div>

app/views/shared/_notifications.html.erb
<div class="toast-container position-fixed top-0 end-0 p-3" id="toast">
  <%= alerts %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p class="mb-0">
      <%= copyright %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">My Portfolio</h1>
      <p class="lead text-body-secondary">In this portfolio, you'll find a showcase of some of my projects developed over the years. Take a look around to see the different types of things I enjoy creating!</p>
      <p>
        <%= link_to "Find Out More About Me", about_path, class: "btn btn-primary my-2" %>
        <%= link_to "My Blog", blogs_path, class: "btn btn-secondary my-2" %>
      </p>
    </div>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>About</h4>
          <p class="text-body-secondary">In this portfolio, you'll find a showcase of some of my projects developed over the years. Each project represents a unique journey and a commitment to excellence in software development. Take a look around to see the different types of things I enjoy creating!</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Explore</h4>
          <ul class="list-unstyled">
            <%= nav_generator("li", "text-white") %>
            <li><%= auth_links("text-white") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>TZ</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_toast.html.erb
<div class="toast align-items-center <%= "#{style}" %> border-0" role="alert" aria-live="assertive" aria-atomic="true" data-controller="flash">
  <div class="d-flex">
    <div class="toast-body">
      <%= msg %>
    </div>
    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>